queries:
  - question: "Who is Achilles and why is he important in the Iliad?"
    keywords: ["achilles", "greek", "warrior", "rage", "hero"]
    domain: "iliad"
  - question: "What causes the quarrel between Agamemnon and Achilles?"
    keywords: ["agamemnon", "achilles", "briseis", "conflict", "honor"]
    domain: "iliad"
  - question: "Describe the role of Hector in the Trojan War."
    keywords: ["hector", "troy", "prince", "warrior", "trojan war"]
    domain: "iliad"
  - question: "What is the significance of Patroclus in the Iliad?"
    keywords: ["patroclus", "achilles", "death", "battle", "friendship"]
    domain: "iliad"
  - question: "How does the Iliad portray the will of the gods and fate?"
    keywords: ["zeus", "apollo", "athena", "fate", "gods"]
    domain: "iliad"
  - question: "What happens during the duel between Paris and Menelaus?"
    keywords: ["paris", "menelaus", "duel", "helen", "battle"]
    domain: "iliad"
  - question: "Why does Achilles refuse to fight, and what brings him back?"
    keywords: ["achilles", "agamemnon", "patroclus", "rage", "return"]
    domain: "iliad"
  - question: "What role do the gods play in the outcome of battles?"
    keywords: ["apollo", "athena", "hera", "zeus", "intervention"]
    domain: "iliad"
  - question: "What is the importance of the armor and shield of Achilles?"
    keywords: ["achilles", "armor", "shield", "hephaestus", "symbol"]
    domain: "iliad"
  - question: "What is the significance of the death of Patroclus?"
    keywords: ["patroclus", "death", "achilles", "hector", "revenge"]
    domain: "iliad"
  - question: "What are the funeral games for Patroclus and their meaning?"
    keywords: ["patroclus", "funeral games", "competition", "honor", "achilles"]
    domain: "iliad"
  - question: "How does Hector die, and what happens to his body?"
    keywords: ["hector", "achilles", "death", "body", "troy"]
    domain: "iliad"
  - question: "What is Priam’s plea to Achilles, and how does Achilles respond?"
    keywords: ["priam", "achilles", "ransom", "hector", "mercy"]
    domain: "iliad"
  - question: "What is the significance of honor and glory (kleos) in the Iliad?"
    keywords: ["kleos", "honor", "glory", "war", "achilles"]
    domain: "iliad"
  - question: "How does the Iliad end?"
    keywords: ["iliad", "ending", "hector", "funeral", "troy"]
    domain: "iliad"
  - question: "What role does Zeus play in the Iliad?"
    keywords: ["zeus", "gods", "fate", "trojans", "greeks"]
    domain: "iliad"
  - question: "What role does Hera play in influencing the war?"
    keywords: ["hera", "zeus", "gods", "greeks", "troy"]
    domain: "iliad"
  - question: "How does Athena intervene in key battles?"
    keywords: ["athena", "battle", "trojans", "greeks", "intervention"]
    domain: "iliad"
  - question: "What role does Apollo play in spreading plague in the Achaean camp?"
    keywords: ["apollo", "plague", "greeks", "agamemnon", "chryses"]
    domain: "iliad"
  - question: "How are women like Helen, Andromache, and Briseis portrayed in the Iliad?"
    keywords: ["helen", "andromache", "briseis", "women", "troy"]
    domain: "iliad"
  - question: "What is the significance of the Catalogue of Ships?"
    keywords: ["catalogue of ships", "greeks", "trojans", "armies", "epic"]
    domain: "iliad"
  - question: "How does the Iliad portray the brutality of war?"
    keywords: ["war", "death", "battle", "bloodshed", "violence"]
    domain: "iliad"