queries:
  - question: "Who is Achilles and why is he important in the Iliad?"
    keywords: ["achilles", "greek", "warrior", "rage", "hero"]
    domain: "iliad"
  - question: "What causes the quarrel between Agamemnon and Achilles?"
    keywords: ["agamemnon", "achilles", "briseis", "conflict", "honor"]
    domain: "iliad"
  - question: "Describe the role of Hector in the Trojan War."
    keywords: ["hector", "troy", "prince", "warrior", "trojan war"]
    domain: "iliad"
  - question: "What is the significance of Patroclus in the Iliad?"
    keywords: ["patroclus", "achilles", "death", "battle", "friendship"]
    domain: "iliad"
  - question: "How does the Iliad portray the will of the gods and fate?"
    keywords: ["zeus", "apollo", "athena", "fate", "gods"]
    domain: "iliad"
  - question: "What happens during the duel between Paris and Menelaus?"
    keywords: ["paris", "menelaus", "duel", "helen", "battle"]
    domain: "iliad"
  - question: "Why does Achilles refuse to fight, and what brings him back?"
    keywords: ["achilles", "agamemnon", "patroclus", "rage", "return"]
    domain: "iliad"
  - question: "What role do the gods play in the outcome of battles?"
    keywords: ["apollo", "athena", "hera", "zeus", "intervention"]
    domain: "iliad"
  - question: "What is the importance of the armor and shield of Achilles?"
    keywords: ["achilles", "armor", "shield", "hephaestus", "symbol"]
    domain: "iliad"
  - question: "What is the significance of the death of Patroclus?"
    keywords: ["patroclus", "death", "achilles", "hector", "revenge"]
    domain: "iliad"
  - question: "What are the funeral games for Patroclus and their meaning?"
    keywords: ["patroclus", "funeral games", "competition", "honor", "achilles"]
    domain: "iliad"
  - question: "How does Hector die, and what happens to his body?"
    keywords: ["hector", "achilles", "death", "body", "troy"]
    domain: "iliad"
  - question: "What is Priam’s plea to Achilles, and how does Achilles respond?"
    keywords: ["priam", "achilles", "ransom", "hector", "mercy"]
    domain: "iliad"
  - question: "What is the significance of honor and glory (kleos) in the Iliad?"
    keywords: ["kleos", "honor", "glory", "war", "achilles"]
    domain: "iliad"
  - question: "How does the Iliad end?"
    keywords: ["iliad", "ending", "hector", "funeral", "troy"]
    domain: "iliad"
  - question: "What role does Zeus play in the Iliad?"
    keywords: ["zeus", "gods", "fate", "trojans", "greeks"]
    domain: "iliad"
  - question: "What role does Hera play in influencing the war?"
    keywords: ["hera", "zeus", "gods", "greeks", "troy"]
    domain: "iliad"
  - question: "How does Athena intervene in key battles?"
    keywords: ["athena", "battle", "trojans", "greeks", "intervention"]
    domain: "iliad"
  - question: "What role does Apollo play in spreading plague in the Achaean camp?"
    keywords: ["apollo", "plague", "greeks", "agamemnon", "chryses"]
    domain: "iliad"
  - question: "How are women like Helen, Andromache, and Briseis portrayed in the Iliad?"
    keywords: ["helen", "andromache", "briseis", "women", "troy"]
    domain: "iliad"
  - question: "What is the significance of the Catalogue of Ships?"
    keywords: ["catalogue of ships", "greeks", "trojans", "armies", "epic"]
    domain: "iliad"
  - question: "How does the Iliad portray the brutality of war?"
    keywords: ["war", "death", "battle", "bloodshed", "violence"]
    domain: "iliad"

  # Beowolf from here on out
  - question: "Who is Beowulf and what are his key heroic deeds?"
    keywords: ["beowulf", "hero", "grendel", "dragon", "warrior"]
    domain: "beowulf"
  - question: "How does Beowulf defeat Grendel?"
    keywords: ["beowulf", "grendel", "fight", "strength", "mead hall"]
    domain: "beowulf"
  - question: "What is the role of Hrothgar in Beowulf?"
    keywords: ["hrothgar", "king", "danes", "heorot", "leader"]
    domain: "beowulf"
  - question: "Describe the battle between Beowulf and Grendel’s mother."
    keywords: ["beowulf", "grendel's mother", "fight", "lake", "sword"]
    domain: "beowulf"
  - question: "What happens during Beowulf’s fight with the dragon?"
    keywords: ["beowulf", "dragon", "battle", "treasure", "death"]
    domain: "beowulf"
  - question: "What themes of loyalty and kinship are present in Beowulf?"
    keywords: ["loyalty", "kinship", "fate", "honor", "thane"]
    domain: "beowulf"
  - question: "How does the poem portray fate (wyrd) and destiny?"
    keywords: ["wyrd", "fate", "destiny", "anglo-saxon", "belief"]
    domain: "beowulf"
  - question: "What role does treasure and gift-giving play in Beowulf?"
    keywords: ["treasure", "gift", "gold", "kingship", "reward"]
    domain: "beowulf"
  - question: "What is the significance of Heorot, Hrothgar’s mead hall?"
    keywords: ["heorot", "hall", "hrothgar", "danes", "mead"]
    domain: "beowulf"
  - question: "How does Beowulf die, and how is he honored after death?"
    keywords: ["beowulf", "death", "funeral", "dragon", "burial"]
    domain: "beowulf"
  - question: "What is the role of Wiglaf in the final battle?"
    keywords: ["wiglaf", "beowulf", "dragon", "loyalty", "thane"]
    domain: "beowulf"
  - question: "What values of Anglo-Saxon warrior culture are reflected in Beowulf?"
    keywords: ["anglo-saxon", "culture", "warrior", "honor", "valor"]
    domain: "beowulf"